_G["db"]["Units"]["Ships"]["Ship"]["#Index"] = {
	DeckLevel = 3,
	DetectionRange = 0,
	DisplayName = "SSK 641B Tango",
	DisplayNameShort = "Tango",
	Gamma_max = 0,
	Height = 9.9,
	IR_emission_coeff = 0.2,
	Length = 91,
	Name = "SSK 641B Tango",
	Om = 0.02,
	RCS = 5000,
	R_min = 182,
	Rate = 1500,
	Sensors = {
		OPTIC = { "long-range naval optics", "long-range naval LLTV" }
	},
	Singleton = "no",
	Tail_Width = 5.2,
	ThreatRange = 0,
	Waypoint_Custom_Panel = true,
	Width = 8.8,
	X_nose = 33.2,
	X_tail = -45.3,
	airFindDist = 0,
	airWeaponDist = 0,
	animation_arguments = {
		arresting_wires = {},
		blast_fences = {},
		water_propeller = -1
	},
	armour_scheme = {
		hull_azimuth = { {} },
		hull_elevation = { {} },
		turret_azimuth = { {} },
		turret_elevation = { {} }
	},
	attribute = { 3, 12, 16, "Redacted", "Submarines", "NO_SAM", "All", "Ships", "Armed ships", "Armed Air Defence", "HeavyArmoredUnits", "Heavy armed ships" },
	chassis = {},
	distFindObstacles = 323,
	economy_distance = 926000,
	economy_velocity = 1.54333,
	life = 300,
	mapclasskey = "P0091000038",
	mass = 3800000,
	max_velocity = 8.23111,
	race_distance = 926000,
	race_velocity = 5.14444,
	shipLength = 91,
	snd = {},
	speedup = 0.124086,
	swapped_names = true,
	tags = { "Submarine" },
	type = "SOM",
	visual = {
		shape = "som",
		shape_dstr = ""
	}
}