_G["bombs"]["#Index"] = {
	Ag = -1.23,
	Cx = 0.00025,
	Name = "Redacted",
	VyHold = -100,
	_file = "./CoreMods/WWII Units/Weapons/Weapons.lua",
	_origin = "World War II AI Units by Eagle Dynamics",
	display_name = "AN-M30A1",
	display_name_short = "M30",
	hMax = 12000,
	hMin = 300,
	mass = 45.8,
	name = "AN_M30A1",
	type = 0,
	warhead = {
		caliber = 207,
		concrete_factors = { 1, 1, 1 },
		concrete_obj_factor = 0,
		cumulative_factor = 0,
		cumulative_thickness = 0,
		default_fuze_delay = 0,
		expl_mass = 18,
		mass = 18,
		obj_factors = { 1, 1 },
		other_factors = { 1, 1, 1 },
		piercing_mass = 3.6
	},
	ws_type = { 4, 5, 9, "Redacted" }
}