_G["bombs"]["#Index"] = {
	Ag = -1.23,
	Cx = 0.00056,
	Name = "Redacted",
	VyHold = -100,
	_file = "./CoreMods/WWII Units/Weapons/Weapons.lua",
	_origin = "World War II AI Units by Eagle Dynamics",
	display_name = "AN-M65",
	display_name_short = "M65",
	hMax = 12000,
	hMin = 300,
	mass = 475,
	name = "AN_M65",
	type = 0,
	warhead = {
		caliber = 477,
		concrete_factors = { 1, 1, 1 },
		concrete_obj_factor = 0,
		cumulative_factor = 0,
		cumulative_thickness = 0,
		default_fuze_delay = 0.01,
		expl_mass = 144,
		mass = 144,
		obj_factors = { 1, 1 },
		other_factors = { 1, 1, 1 },
		piercing_mass = 28.8
	},
	ws_type = { 4, 5, 9, "Redacted" }
}