_G["bombs"]["#Index"] = {
	Ag = -5,
	Cx = 0.0006,
	Name = "Redacted",
	VyHold = -50,
	_file = "./CoreMods/aircraft/AircraftWeaponPack/common_bombs.lua",
	_origin = "AircraftWeaponPack",
	display_name = "BAP-100",
	display_name_short = "BAP-100",
	hMax = 3000,
	hMin = 40,
	mass = 32.5,
	name = "BAP-100",
	type = 1,
	warhead = {
		caliber = 100,
		concrete_factors = { 3.5, 1, 5 },
		concrete_obj_factor = 10,
		cumulative_factor = 0,
		cumulative_thickness = 0,
		default_fuze_delay = 0.5,
		expl_mass = 3.5,
		mass = 18,
		obj_factors = { 0.1, 0.1, 0.1 },
		other_factors = { 0.5, 0.5, 1 },
		piercing_mass = 3.6
	},
	ws_type = { 4, 5, 37, "Redacted" }
}