_G["bombs"]["#Index"] = {
	Ag = -1.23,
	Cx = 0.00133,
	Name = "Redacted",
	VyHold = -100,
	_file = "./CoreMods/WWII Units/Weapons/Weapons.lua",
	_origin = "World War II AI Units by Eagle Dynamics",
	display_name = "500 lb S.A.P.",
	display_name_short = "500 lb S.A.P.",
	hMax = 12000,
	hMin = 300,
	mass = 222.26,
	name = "British_SAP_500LB_Bomb_Mk5",
	type = 0,
	warhead = {
		caliber = 292,
		concrete_factors = { 1, 1, 1 },
		concrete_obj_factor = 0.5,
		cumulative_factor = 2.5,
		cumulative_thickness = 0.2,
		default_fuze_delay = 0.01,
		expl_mass = 44,
		mass = 44,
		obj_factors = { 1, 1 },
		other_factors = { 1, 1, 1 },
		piercing_mass = 8.8
	},
	ws_type = { 4, 5, 9, "Redacted" }
}