_G["bombs"]["#Index"] = {
	Ag = -1,
	Cx = 0.00133,
	Name = "Redacted",
	VyHold = -80,
	_file = "./CoreMods/aircraft/AircraftWeaponPack/KABs.lua",
	_origin = "AircraftWeaponPack",
	display_name = "KAB-500S",
	display_name_short = "KAB-500",
	hMax = 10000,
	hMin = 1000,
	mass = 500,
	name = "KAB_500S",
	type = 6,
	warhead = {
		caliber = 400,
		concrete_factors = { 1, 1, 1 },
		concrete_obj_factor = 0,
		cumulative_factor = 0,
		cumulative_thickness = 0,
		default_fuze_delay = 0,
		expl_mass = 184,
		mass = 184,
		obj_factors = { 1, 1 },
		other_factors = { 1, 1, 1 },
		piercing_mass = 36.8
	},
	ws_type = { 4, 5, 36, "Redacted" }
}