_G["bombs"]["#Index"] = {
	Ag = -1,
	Cx = 0.00436,
	Name = "Redacted",
	VyHold = -80,
	_file = "./CoreMods/aircraft/AircraftWeaponPack/KABs.lua",
	_origin = "AircraftWeaponPack",
	display_name = "KAB-1500Kr",
	display_name_short = "KAB-1500",
	hMax = 15000,
	hMin = 1000,
	mass = 1525,
	name = "KAB_1500T",
	type = 3,
	warhead = {
		caliber = 580,
		concrete_factors = { 1, 1, 1 },
		concrete_obj_factor = 0,
		cumulative_factor = 0,
		cumulative_thickness = 0,
		default_fuze_delay = 0,
		expl_mass = 468,
		mass = 468,
		obj_factors = { 1, 1 },
		other_factors = { 1, 1, 1 },
		piercing_mass = 93.6
	},
	ws_type = { 4, 5, 36, "Redacted" }
}