_G["bombs"]["#Index"] = {
	Ag = -1.23,
	Cx = 0.00018,
	Name = "Redacted",
	VyHold = -100,
	_file = "./CoreMods/aircraft/L-39/L-39ZA.lua",
	_origin = "L-39C/ZA by Eagle Dynamics",
	display_name = "OFAB-100 Jupiter - 100kg GP Bomb HD",
	display_name_short = "OFAB-100 Jupiter - 100kg GP Bomb HD",
	hMax = 12000,
	hMin = 50,
	mass = 121,
	name = "OFAB-100 Jupiter",
	type = 0,
	warhead = {
		caliber = 273,
		concrete_factors = { 1, 1, 1 },
		concrete_obj_factor = 0,
		cumulative_factor = 0,
		cumulative_thickness = 0,
		default_fuze_delay = 0,
		expl_mass = 36,
		mass = 36,
		obj_factors = { 1, 1 },
		other_factors = { 1, 1, 1 },
		piercing_mass = 7.2
	},
	ws_type = { 4, 5, 9, "Redacted" }
}