_G["bombs"]["#Index"] = {
	Ag = -20,
	Cx = 0.00018,
	Name = "Redacted",
	VyHold = -75,
	_file = "./CoreMods/aircraft/AircraftWeaponPack/common_bombs.lua",
	_origin = "AircraftWeaponPack",
	display_name = "TYPE-200A",
	display_name_short = "T200",
	hMax = 5000,
	hMin = 60,
	mass = 200,
	name = "Type_200A",
	type = 1,
	warhead = {
		caliber = 223,
		concrete_factors = { 5, 1, 5 },
		concrete_obj_factor = 10,
		cumulative_factor = 0,
		cumulative_thickness = 0,
		default_fuze_delay = 0.5,
		expl_mass = 90,
		mass = 130,
		obj_factors = { 1, 1, 1 },
		other_factors = { 0.5, 0.5, 1 },
		piercing_mass = 26
	},
	ws_type = { 4, 5, 37, "Redacted" }
}