_G["db"]["Units"]["Heliports"]["Heliport"]["#Index"] = {
	DisplayName = "PAD Single",
	Life = 2500,
	Name = "PAD Single",
	Rate = 100,
	SeaObject = true,
	ShapeName = "FARP_SINGLE_01",
	_file = "./CoreMods/tech/SouthAtlanticAssets/Entries/Static/farpsingle.lua",
	_origin = "South_Atlantic_Assets",
	attribute = { 5, 9 },
	category = "Heliport",
	classname = "lOilPlatform",
	enablePlayerCanDrive = false,
	isPutToWater = true,
	mapclasskey = "P0091000022",
	numParking = 1,
	positioning = "YES",
	shape_table_data = { {
			classname = "lOilPlatform",
			desrt = "self",
			file = "FARP_SINGLE_01",
			life = 2500,
			name = "FARP_SINGLE_01",
			positioning = "YES",
			username = "FARP_SINGLE_01"
		} },
	swapped_names = true,
	type = "FARP_SINGLE_01"
}