_G["db"]["Units"]["Heliports"]["Heliport"]["#Index"] = {
	DisplayName = "Gas platform",
	Life = 2500,
	Name = "Gas platform",
	Rate = 100,
	SeaObject = true,
	ShapeName = "gas_platform",
	_file = "./CoreMods/tech/TechWeaponPack/Database/db_ground_objects.lua",
	_origin = "TechWeaponPack",
	attribute = { 5, 9 },
	category = "Heliport",
	classname = "lGasPlatform",
	enablePlayerCanDrive = false,
	isPutToWater = true,
	mapclasskey = "P0091000076",
	numParking = 1,
	positioning = "NO",
	shape_table_data = { {
			classname = "lGasPlatform",
			desrt = "self",
			file = "gas_platform",
			life = 2500,
			name = "gas_platform",
			positioning = "NO",
			username = "Gas platform"
		} },
	subCategory = "SeaShelfObject",
	type = "Gas platform"
}